"""encrypt user table

Revision ID: 8512a89a85cc
Revises: 94d70a663c0f
Create Date: 2025-12-12 22:26:44.931768

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8512a89a85cc'
down_revision: Union[str, Sequence[str], None] = '94d70a663c0f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email_hash', sa.String(length=64), nullable=False))
    op.alter_column('users', 'full_name',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=512),
               existing_nullable=False)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=320),
               type_=sa.String(length=512),
               existing_nullable=False)
    op.create_index(op.f('ix_users_email_hash'), 'users', ['email_hash'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email_hash'), table_name='users')
    op.alter_column('users', 'email',
               existing_type=sa.String(length=512),
               type_=sa.VARCHAR(length=320),
               existing_nullable=False)
    op.alter_column('users', 'full_name',
               existing_type=sa.String(length=512),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.drop_column('users', 'email_hash')
    # ### end Alembic commands ###
