"""encrypt table schedule

Revision ID: bd36a9df27a8
Revises: 8512a89a85cc
Create Date: 2025-12-12 22:33:23.987673

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd36a9df27a8'
down_revision: Union[str, Sequence[str], None] = '8512a89a85cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('schedules', 'purpose',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=512),
               existing_nullable=False)
    op.alter_column('schedules', 'team_members',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=1024),
               existing_nullable=True)
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.alter_column('schedules', 'team_members',
               existing_type=sa.String(length=1024),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)
    op.alter_column('schedules', 'purpose',
               existing_type=sa.String(length=512),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    # ### end Alembic commands ###
