"""remove endtime schedule

Revision ID: bde6be0afc87
Revises: fe2730a6a762
Create Date: 2025-12-09 14:49:42.149317

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bde6be0afc87'
down_revision: Union[str, Sequence[str], None] = 'fe2730a6a762'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('schedules', 'end_time')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('schedules', sa.Column('end_time', postgresql.TIME(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
